sonarqube flow add check quality gate

diff --git a/.github/workflows/_sonarqube.yml b/.github/workflows/_sonarqube.yml
--- a/.github/workflows/_sonarqube.yml
+++ b/.github/workflows/_sonarqube.yml
@@ -51,3 +51,34 @@ jobs:
               #-Dsonar.tests= # optional. For more info about Code Coverage, please refer to https://docs.sonarcloud.io/enriching/test-coverage/overview/
               # Adds more detail to both client and server-side analysis logs, activating DEBUG mode for the scanner, and adding client-side environment variables and system properties to the server-side log of analysis report processing.
               #-Dsonar.verbose= # optional, default is false
+
+  scan-quality-gate:
+    runs-on: ubuntu-latest
+    needs: sonarqube-scan
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: Set up JDK 11
+        uses: actions/setup-java@v2
+        with:
+          distribution: 'temurin'
+          java-version: '11'
+
+      - name: Check Quality Gate
+        env:
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+        run: |
+          # Wait for the background task to finish
+          sleep 20
+          # Fetch analysis ID
+          ANALYSIS_ID=$(curl -s -u $SONAR_TOKEN: "${{ secrets.SONAR_HOST_URL }}/api/ce/task?id=$(curl -s -u $SONAR_TOKEN: '${{ secrets.SONAR_HOST_URL }}/api/ce/component?component='${{ inputs.projectKey }}'&maxResults=1' | jq -r '.currentComponent.analyses[0].id')" | jq -r '.task.analysisId')
+          # Fetch Quality Gate status
+          STATUS=$(curl -s -u $SONAR_TOKEN: "${{ secrets.SONAR_HOST_URL }}/api/qualitygates/project_status?analysisId=$ANALYSIS_ID" | jq -r '.projectStatus.status')
+          # Fail the pipeline if Quality Gate fails
+          if [ "$STATUS" != "OK" ]; then
+            echo "Quality Gate failed: $STATUS"
+            exit 1
+          else
+            echo "Quality Gate passed: $STATUS"
+          fi
